plugins {
    id "com.android.application"
}

android {
    namespace "com.minimalus.mobile.v1"
    compileSdk 35

    defaultConfig {
        applicationId "com.minimalus.mobile.v1"
        minSdk 24
        targetSdk 35
        versionCode 106
        versionName "1.0.6"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
